[build]
  command = "npm install && cd frontend && npm install && npm run build"
  publish = "frontend/.next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Forza il plugin Next.js per il riconoscimento del framework
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"

# Headers per sicurezza e performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configurazione semplificata delle redirects per le API
# Un singolo redirect generico per evitare conflitti
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 